# Generated by Django 5.0.2 on 2024-03-13 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_talk'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Talk',
            new_name='Data',
        ),
    ]
