# Generated by Django 5.0.2 on 2024-04-20 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_talk_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='talk_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_data_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='data',
            name='talk_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_data_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
